/* tslint:disable */
/* eslint-disable */
/**
 * KaguERP.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type PartyReportQueryApiRequest,
    PartyReportQueryApiRequestFromJSON,
    PartyReportQueryApiRequestToJSON,
} from '../models/PartyReportQueryApiRequest';

export interface QueryPartyAccountReportRequest {
    code: string;
    partyReportQueryApiRequest: PartyReportQueryApiRequest;
}

/**
 *
 */
export class PartyReportQueryEndpointApi extends runtime.BaseAPI {

    /**
     * Creates request options for queryPartyAccountReport without sending the request
     */
    async queryPartyAccountReportRequestOpts(requestParameters: QueryPartyAccountReportRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling queryPartyAccountReport().'
            );
        }

        if (requestParameters['partyReportQueryApiRequest'] == null) {
            throw new runtime.RequiredError(
                'partyReportQueryApiRequest',
                'Required parameter "partyReportQueryApiRequest" was null or undefined when calling queryPartyAccountReport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/reports/{code}/queries`;
        urlPath = urlPath.replace('{code}', encodeURIComponent(String(requestParameters['code'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PartyReportQueryApiRequestToJSON(requestParameters['partyReportQueryApiRequest']),
        };
    }

    /**
     */
    async queryPartyAccountReportRaw(requestParameters: QueryPartyAccountReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.queryPartyAccountReportRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async queryPartyAccountReport(requestParameters: QueryPartyAccountReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.queryPartyAccountReportRaw(requestParameters, initOverrides);
    }

}
