/* tslint:disable */
/* eslint-disable */
/**
 * KaguERP.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ApiProblemResponse,
    ApiProblemResponseFromJSON,
    ApiProblemResponseToJSON,
} from '../models/ApiProblemResponse';
import {
    type SalesOrderCreateApiRequest,
    SalesOrderCreateApiRequestFromJSON,
    SalesOrderCreateApiRequestToJSON,
} from '../models/SalesOrderCreateApiRequest';
import {
    type SalesOrderLifecycleApiResponse,
    SalesOrderLifecycleApiResponseFromJSON,
    SalesOrderLifecycleApiResponseToJSON,
} from '../models/SalesOrderLifecycleApiResponse';
import {
    type SalesOrderTransitionApiRequest,
    SalesOrderTransitionApiRequestFromJSON,
    SalesOrderTransitionApiRequestToJSON,
} from '../models/SalesOrderTransitionApiRequest';

export interface CreateSalesOrderDraftRequest {
    idempotencyKey: string;
    salesOrderCreateApiRequest: SalesOrderCreateApiRequest;
}

export interface GetSalesOrderLifecycleRequest {
    orderId: string;
    companyId: string;
}

export interface TransitionSalesOrderRequest {
    orderId: string;
    action: TransitionSalesOrderActionEnum;
    idempotencyKey: string;
    ifMatch: string;
    salesOrderTransitionApiRequest: SalesOrderTransitionApiRequest;
}

/**
 *
 */
export class SalesOrdersApi extends runtime.BaseAPI {

    /**
     * Creates request options for createSalesOrderDraft without sending the request
     */
    async createSalesOrderDraftRequestOpts(requestParameters: CreateSalesOrderDraftRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createSalesOrderDraft().'
            );
        }

        if (requestParameters['salesOrderCreateApiRequest'] == null) {
            throw new runtime.RequiredError(
                'salesOrderCreateApiRequest',
                'Required parameter "salesOrderCreateApiRequest" was null or undefined when calling createSalesOrderDraft().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sales-orders`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SalesOrderCreateApiRequestToJSON(requestParameters['salesOrderCreateApiRequest']),
        };
    }

    /**
     * Uses the canonical UUID Idempotency-Key as the sales-order identity.
     * Create a draft sales order
     */
    async createSalesOrderDraftRaw(requestParameters: CreateSalesOrderDraftRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SalesOrderLifecycleApiResponse>> {
        const requestOptions = await this.createSalesOrderDraftRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SalesOrderLifecycleApiResponseFromJSON(jsonValue));
    }

    /**
     * Uses the canonical UUID Idempotency-Key as the sales-order identity.
     * Create a draft sales order
     */
    async createSalesOrderDraft(requestParameters: CreateSalesOrderDraftRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SalesOrderLifecycleApiResponse> {
        const response = await this.createSalesOrderDraftRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSalesOrderLifecycle without sending the request
     */
    async getSalesOrderLifecycleRequestOpts(requestParameters: GetSalesOrderLifecycleRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling getSalesOrderLifecycle().'
            );
        }

        if (requestParameters['companyId'] == null) {
            throw new runtime.RequiredError(
                'companyId',
                'Required parameter "companyId" was null or undefined when calling getSalesOrderLifecycle().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['companyId'] != null) {
            queryParameters['companyId'] = requestParameters['companyId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sales-orders/{orderId}`;
        urlPath = urlPath.replace('{orderId}', encodeURIComponent(String(requestParameters['orderId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a sales order lifecycle
     */
    async getSalesOrderLifecycleRaw(requestParameters: GetSalesOrderLifecycleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SalesOrderLifecycleApiResponse>> {
        const requestOptions = await this.getSalesOrderLifecycleRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SalesOrderLifecycleApiResponseFromJSON(jsonValue));
    }

    /**
     * Get a sales order lifecycle
     */
    async getSalesOrderLifecycle(requestParameters: GetSalesOrderLifecycleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SalesOrderLifecycleApiResponse> {
        const response = await this.getSalesOrderLifecycleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for transitionSalesOrder without sending the request
     */
    async transitionSalesOrderRequestOpts(requestParameters: TransitionSalesOrderRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling transitionSalesOrder().'
            );
        }

        if (requestParameters['action'] == null) {
            throw new runtime.RequiredError(
                'action',
                'Required parameter "action" was null or undefined when calling transitionSalesOrder().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling transitionSalesOrder().'
            );
        }

        if (requestParameters['ifMatch'] == null) {
            throw new runtime.RequiredError(
                'ifMatch',
                'Required parameter "ifMatch" was null or undefined when calling transitionSalesOrder().'
            );
        }

        if (requestParameters['salesOrderTransitionApiRequest'] == null) {
            throw new runtime.RequiredError(
                'salesOrderTransitionApiRequest',
                'Required parameter "salesOrderTransitionApiRequest" was null or undefined when calling transitionSalesOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (requestParameters['ifMatch'] != null) {
            headerParameters['If-Match'] = String(requestParameters['ifMatch']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/sales-orders/{orderId}/{action}`;
        urlPath = urlPath.replace('{orderId}', encodeURIComponent(String(requestParameters['orderId'])));
        urlPath = urlPath.replace('{action}', encodeURIComponent(String(requestParameters['action'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SalesOrderTransitionApiRequestToJSON(requestParameters['salesOrderTransitionApiRequest']),
        };
    }

    /**
     * Requires a canonical UUID Idempotency-Key and a quoted positive If-Match version.
     * Apply a sales order lifecycle transition
     */
    async transitionSalesOrderRaw(requestParameters: TransitionSalesOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SalesOrderLifecycleApiResponse>> {
        const requestOptions = await this.transitionSalesOrderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SalesOrderLifecycleApiResponseFromJSON(jsonValue));
    }

    /**
     * Requires a canonical UUID Idempotency-Key and a quoted positive If-Match version.
     * Apply a sales order lifecycle transition
     */
    async transitionSalesOrder(requestParameters: TransitionSalesOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SalesOrderLifecycleApiResponse> {
        const response = await this.transitionSalesOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
  * @export
  * @enum {string}
  */
export enum TransitionSalesOrderActionEnum {
    Submit = 'submit',
    Approve = 'approve',
    Reject = 'reject',
    Withdraw = 'withdraw',
    Revise = 'revise',
    Confirm = 'confirm',
    Cancel = 'cancel',
    Close = 'close'
}
