<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BuildingBlocks\Application\KaguERP.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\BuildingBlocks\Contracts\KaguERP.BuildingBlocks.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\Erp.Bootstrap\*.cs" LinkBase="Bootstrap" />
  </ItemGroup>
</Project>
