<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BuildingBlocks\Application\KaguERP.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\BuildingBlocks\Contracts\KaguERP.BuildingBlocks.Contracts.csproj" />
    <ProjectReference Include="..\Erp.Bootstrap\KaguERP.Bootstrap.csproj" PrivateAssets="all" />
    <ProjectReference Include="..\Modules\Reporting\Reporting.Application\KaguERP.Modules.Reporting.Application.csproj" PrivateAssets="all" />
  </ItemGroup>
</Project>
