/* tslint:disable */
/* eslint-disable */
/**
 * KaguERP.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ApiProblemResponse
 */
export interface ApiProblemResponse {
    /**
     *
     * @type {string}
     * @memberof ApiProblemResponse
     */
    type: string;
    /**
     *
     * @type {string}
     * @memberof ApiProblemResponse
     */
    title: string;
    /**
     *
     * @type {number}
     * @memberof ApiProblemResponse
     */
    status: number;
    /**
     *
     * @type {string}
     * @memberof ApiProblemResponse
     */
    code: string;
    /**
     *
     * @type {string}
     * @memberof ApiProblemResponse
     */
    traceId: string;
    /**
     *
     * @type {string}
     * @memberof ApiProblemResponse
     */
    correlationId: string | null;
}

/**
 * Check if a given object implements the ApiProblemResponse interface.
 */
export function instanceOfApiProblemResponse(value: object): value is ApiProblemResponse {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('traceId' in value) || value['traceId'] === undefined) return false;
    if (!('correlationId' in value) || value['correlationId'] === undefined) return false;
    return true;
}

export function ApiProblemResponseFromJSON(json: any): ApiProblemResponse {
    return ApiProblemResponseFromJSONTyped(json, false);
}

export function ApiProblemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiProblemResponse {
    if (json == null) {
        return json;
    }
    return {

        'type': json['type'],
        'title': json['title'],
        'status': json['status'],
        'code': json['code'],
        'traceId': json['traceId'],
        'correlationId': json['correlationId'],
    };
}

export function ApiProblemResponseToJSON(json: any): ApiProblemResponse {
    return ApiProblemResponseToJSONTyped(json, false);
}

export function ApiProblemResponseToJSONTyped(value?: ApiProblemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'type': value['type'],
        'title': value['title'],
        'status': value['status'],
        'code': value['code'],
        'traceId': value['traceId'],
        'correlationId': value['correlationId'],
    };
}
