/* tslint:disable */
/* eslint-disable */
/**
 * KaguERP.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PartyReportQueryApiRequest
 */
export interface PartyReportQueryApiRequest {
    /**
     *
     * @type {string}
     * @memberof PartyReportQueryApiRequest
     */
    companyId: string;
    /**
     *
     * @type {string}
     * @memberof PartyReportQueryApiRequest
     */
    statementId: string;
    /**
     *
     * @type {string}
     * @memberof PartyReportQueryApiRequest
     */
    agingReportId: string;
}

/**
 * Check if a given object implements the PartyReportQueryApiRequest interface.
 */
export function instanceOfPartyReportQueryApiRequest(value: object): value is PartyReportQueryApiRequest {
    if (!('companyId' in value) || value['companyId'] === undefined) return false;
    if (!('statementId' in value) || value['statementId'] === undefined) return false;
    if (!('agingReportId' in value) || value['agingReportId'] === undefined) return false;
    return true;
}

export function PartyReportQueryApiRequestFromJSON(json: any): PartyReportQueryApiRequest {
    return PartyReportQueryApiRequestFromJSONTyped(json, false);
}

export function PartyReportQueryApiRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartyReportQueryApiRequest {
    if (json == null) {
        return json;
    }
    return {

        'companyId': json['companyId'],
        'statementId': json['statementId'],
        'agingReportId': json['agingReportId'],
    };
}

export function PartyReportQueryApiRequestToJSON(json: any): PartyReportQueryApiRequest {
    return PartyReportQueryApiRequestToJSONTyped(json, false);
}

export function PartyReportQueryApiRequestToJSONTyped(value?: PartyReportQueryApiRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'companyId': value['companyId'],
        'statementId': value['statementId'],
        'agingReportId': value['agingReportId'],
    };
}
