/* tslint:disable */
/* eslint-disable */
/**
 * KaguERP.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SalesOrderLineApiResponse
 */
export interface SalesOrderLineApiResponse {
    /**
     *
     * @type {string}
     * @memberof SalesOrderLineApiResponse
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof SalesOrderLineApiResponse
     */
    itemId: string;
    /**
     *
     * @type {string}
     * @memberof SalesOrderLineApiResponse
     */
    baseUomCode: string;
    /**
     *
     * @type {string}
     * @memberof SalesOrderLineApiResponse
     */
    orderedBaseQuantity: string;
}

/**
 * Check if a given object implements the SalesOrderLineApiResponse interface.
 */
export function instanceOfSalesOrderLineApiResponse(value: object): value is SalesOrderLineApiResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    if (!('baseUomCode' in value) || value['baseUomCode'] === undefined) return false;
    if (!('orderedBaseQuantity' in value) || value['orderedBaseQuantity'] === undefined) return false;
    return true;
}

export function SalesOrderLineApiResponseFromJSON(json: any): SalesOrderLineApiResponse {
    return SalesOrderLineApiResponseFromJSONTyped(json, false);
}

export function SalesOrderLineApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SalesOrderLineApiResponse {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'itemId': json['itemId'],
        'baseUomCode': json['baseUomCode'],
        'orderedBaseQuantity': json['orderedBaseQuantity'],
    };
}

export function SalesOrderLineApiResponseToJSON(json: any): SalesOrderLineApiResponse {
    return SalesOrderLineApiResponseToJSONTyped(json, false);
}

export function SalesOrderLineApiResponseToJSONTyped(value?: SalesOrderLineApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'itemId': value['itemId'],
        'baseUomCode': value['baseUomCode'],
        'orderedBaseQuantity': value['orderedBaseQuantity'],
    };
}
