/* tslint:disable */
/* eslint-disable */
/**
 * KaguERP.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SalesOrderLineCreateApiRequest } from './SalesOrderLineCreateApiRequest';
import {
    SalesOrderLineCreateApiRequestFromJSON,
    SalesOrderLineCreateApiRequestFromJSONTyped,
    SalesOrderLineCreateApiRequestToJSON,
    SalesOrderLineCreateApiRequestToJSONTyped,
} from './SalesOrderLineCreateApiRequest';

/**
 *
 * @export
 * @interface SalesOrderCreateApiRequest
 */
export interface SalesOrderCreateApiRequest {
    /**
     *
     * @type {string}
     * @memberof SalesOrderCreateApiRequest
     */
    companyId: string;
    /**
     *
     * @type {Array<SalesOrderLineCreateApiRequest>}
     * @memberof SalesOrderCreateApiRequest
     */
    lines: Array<SalesOrderLineCreateApiRequest>;
}

/**
 * Check if a given object implements the SalesOrderCreateApiRequest interface.
 */
export function instanceOfSalesOrderCreateApiRequest(value: object): value is SalesOrderCreateApiRequest {
    if (!('companyId' in value) || value['companyId'] === undefined) return false;
    if (!('lines' in value) || value['lines'] === undefined) return false;
    return true;
}

export function SalesOrderCreateApiRequestFromJSON(json: any): SalesOrderCreateApiRequest {
    return SalesOrderCreateApiRequestFromJSONTyped(json, false);
}

export function SalesOrderCreateApiRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SalesOrderCreateApiRequest {
    if (json == null) {
        return json;
    }
    return {

        'companyId': json['companyId'],
        'lines': ((json['lines'] as Array<any>).map(SalesOrderLineCreateApiRequestFromJSON)),
    };
}

export function SalesOrderCreateApiRequestToJSON(json: any): SalesOrderCreateApiRequest {
    return SalesOrderCreateApiRequestToJSONTyped(json, false);
}

export function SalesOrderCreateApiRequestToJSONTyped(value?: SalesOrderCreateApiRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'companyId': value['companyId'],
        'lines': ((value['lines'] as Array<any>).map(SalesOrderLineCreateApiRequestToJSON)),
    };
}
