/* tslint:disable */
/* eslint-disable */
/**
 * KaguERP.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SalesOrderTransitionApiRequest
 */
export interface SalesOrderTransitionApiRequest {
    /**
     *
     * @type {string}
     * @memberof SalesOrderTransitionApiRequest
     */
    companyId: string;
    /**
     *
     * @type {string}
     * @memberof SalesOrderTransitionApiRequest
     */
    reason: string | null;
}

/**
 * Check if a given object implements the SalesOrderTransitionApiRequest interface.
 */
export function instanceOfSalesOrderTransitionApiRequest(value: object): value is SalesOrderTransitionApiRequest {
    if (!('companyId' in value) || value['companyId'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function SalesOrderTransitionApiRequestFromJSON(json: any): SalesOrderTransitionApiRequest {
    return SalesOrderTransitionApiRequestFromJSONTyped(json, false);
}

export function SalesOrderTransitionApiRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SalesOrderTransitionApiRequest {
    if (json == null) {
        return json;
    }
    return {

        'companyId': json['companyId'],
        'reason': json['reason'],
    };
}

export function SalesOrderTransitionApiRequestToJSON(json: any): SalesOrderTransitionApiRequest {
    return SalesOrderTransitionApiRequestToJSONTyped(json, false);
}

export function SalesOrderTransitionApiRequestToJSONTyped(value?: SalesOrderTransitionApiRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'companyId': value['companyId'],
        'reason': value['reason'],
    };
}
