/* tslint:disable */
/* eslint-disable */
/**
 * KaguERP.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SalesOrderTransitionApiResponse
 */
export interface SalesOrderTransitionApiResponse {
    /**
     *
     * @type {string}
     * @memberof SalesOrderTransitionApiResponse
     */
    eventId: string;
    /**
     *
     * @type {string}
     * @memberof SalesOrderTransitionApiResponse
     */
    transition: string;
    /**
     *
     * @type {number}
     * @memberof SalesOrderTransitionApiResponse
     */
    previousVersion: number;
    /**
     *
     * @type {number}
     * @memberof SalesOrderTransitionApiResponse
     */
    newVersion: number;
    /**
     *
     * @type {Date}
     * @memberof SalesOrderTransitionApiResponse
     */
    occurredAt: Date;
    /**
     *
     * @type {string}
     * @memberof SalesOrderTransitionApiResponse
     */
    reason: string | null;
}

/**
 * Check if a given object implements the SalesOrderTransitionApiResponse interface.
 */
export function instanceOfSalesOrderTransitionApiResponse(value: object): value is SalesOrderTransitionApiResponse {
    if (!('eventId' in value) || value['eventId'] === undefined) return false;
    if (!('transition' in value) || value['transition'] === undefined) return false;
    if (!('previousVersion' in value) || value['previousVersion'] === undefined) return false;
    if (!('newVersion' in value) || value['newVersion'] === undefined) return false;
    if (!('occurredAt' in value) || value['occurredAt'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function SalesOrderTransitionApiResponseFromJSON(json: any): SalesOrderTransitionApiResponse {
    return SalesOrderTransitionApiResponseFromJSONTyped(json, false);
}

export function SalesOrderTransitionApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SalesOrderTransitionApiResponse {
    if (json == null) {
        return json;
    }
    return {

        'eventId': json['eventId'],
        'transition': json['transition'],
        'previousVersion': json['previousVersion'],
        'newVersion': json['newVersion'],
        'occurredAt': (new Date(json['occurredAt'])),
        'reason': json['reason'],
    };
}

export function SalesOrderTransitionApiResponseToJSON(json: any): SalesOrderTransitionApiResponse {
    return SalesOrderTransitionApiResponseToJSONTyped(json, false);
}

export function SalesOrderTransitionApiResponseToJSONTyped(value?: SalesOrderTransitionApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'eventId': value['eventId'],
        'transition': value['transition'],
        'previousVersion': value['previousVersion'],
        'newVersion': value['newVersion'],
        'occurredAt': value['occurredAt'].toISOString(),
        'reason': value['reason'],
    };
}
