/* tslint:disable */
/* eslint-disable */
/**
 * KaguERP.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SalesOrderLineCreateApiRequest
 */
export interface SalesOrderLineCreateApiRequest {
    /**
     *
     * @type {string}
     * @memberof SalesOrderLineCreateApiRequest
     */
    orderLineId: string;
    /**
     *
     * @type {string}
     * @memberof SalesOrderLineCreateApiRequest
     */
    itemId: string;
    /**
     *
     * @type {string}
     * @memberof SalesOrderLineCreateApiRequest
     */
    baseUomCode: string;
    /**
     *
     * @type {string}
     * @memberof SalesOrderLineCreateApiRequest
     */
    orderedBaseQuantity: string;
}

/**
 * Check if a given object implements the SalesOrderLineCreateApiRequest interface.
 */
export function instanceOfSalesOrderLineCreateApiRequest(value: object): value is SalesOrderLineCreateApiRequest {
    if (!('orderLineId' in value) || value['orderLineId'] === undefined) return false;
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    if (!('baseUomCode' in value) || value['baseUomCode'] === undefined) return false;
    if (!('orderedBaseQuantity' in value) || value['orderedBaseQuantity'] === undefined) return false;
    return true;
}

export function SalesOrderLineCreateApiRequestFromJSON(json: any): SalesOrderLineCreateApiRequest {
    return SalesOrderLineCreateApiRequestFromJSONTyped(json, false);
}

export function SalesOrderLineCreateApiRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SalesOrderLineCreateApiRequest {
    if (json == null) {
        return json;
    }
    return {

        'orderLineId': json['orderLineId'],
        'itemId': json['itemId'],
        'baseUomCode': json['baseUomCode'],
        'orderedBaseQuantity': json['orderedBaseQuantity'],
    };
}

export function SalesOrderLineCreateApiRequestToJSON(json: any): SalesOrderLineCreateApiRequest {
    return SalesOrderLineCreateApiRequestToJSONTyped(json, false);
}

export function SalesOrderLineCreateApiRequestToJSONTyped(value?: SalesOrderLineCreateApiRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'orderLineId': value['orderLineId'],
        'itemId': value['itemId'],
        'baseUomCode': value['baseUomCode'],
        'orderedBaseQuantity': value['orderedBaseQuantity'],
    };
}
