/* tslint:disable */
/* eslint-disable */
/**
 * KaguERP.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SalesOrderLineApiResponse } from './SalesOrderLineApiResponse';
import {
    SalesOrderLineApiResponseFromJSON,
    SalesOrderLineApiResponseFromJSONTyped,
    SalesOrderLineApiResponseToJSON,
    SalesOrderLineApiResponseToJSONTyped,
} from './SalesOrderLineApiResponse';
import type { SalesOrderTransitionApiResponse } from './SalesOrderTransitionApiResponse';
import {
    SalesOrderTransitionApiResponseFromJSON,
    SalesOrderTransitionApiResponseFromJSONTyped,
    SalesOrderTransitionApiResponseToJSON,
    SalesOrderTransitionApiResponseToJSONTyped,
} from './SalesOrderTransitionApiResponse';

/**
 *
 * @export
 * @interface SalesOrderLifecycleApiResponse
 */
export interface SalesOrderLifecycleApiResponse {
    /**
     *
     * @type {string}
     * @memberof SalesOrderLifecycleApiResponse
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof SalesOrderLifecycleApiResponse
     */
    companyId: string;
    /**
     *
     * @type {string}
     * @memberof SalesOrderLifecycleApiResponse
     */
    makerId: string;
    /**
     *
     * @type {string}
     * @memberof SalesOrderLifecycleApiResponse
     */
    status: string;
    /**
     *
     * @type {number}
     * @memberof SalesOrderLifecycleApiResponse
     */
    version: number;
    /**
     *
     * @type {Array<SalesOrderLineApiResponse>}
     * @memberof SalesOrderLifecycleApiResponse
     */
    lines: Array<SalesOrderLineApiResponse>;
    /**
     *
     * @type {Array<SalesOrderTransitionApiResponse>}
     * @memberof SalesOrderLifecycleApiResponse
     */
    transitions: Array<SalesOrderTransitionApiResponse> | null;
}

/**
 * Check if a given object implements the SalesOrderLifecycleApiResponse interface.
 */
export function instanceOfSalesOrderLifecycleApiResponse(value: object): value is SalesOrderLifecycleApiResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('companyId' in value) || value['companyId'] === undefined) return false;
    if (!('makerId' in value) || value['makerId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('lines' in value) || value['lines'] === undefined) return false;
    if (!('transitions' in value) || value['transitions'] === undefined) return false;
    return true;
}

export function SalesOrderLifecycleApiResponseFromJSON(json: any): SalesOrderLifecycleApiResponse {
    return SalesOrderLifecycleApiResponseFromJSONTyped(json, false);
}

export function SalesOrderLifecycleApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SalesOrderLifecycleApiResponse {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'],
        'companyId': json['companyId'],
        'makerId': json['makerId'],
        'status': json['status'],
        'version': json['version'],
        'lines': ((json['lines'] as Array<any>).map(SalesOrderLineApiResponseFromJSON)),
        'transitions': (json['transitions'] == null ? null : (json['transitions'] as Array<any>).map(SalesOrderTransitionApiResponseFromJSON)),
    };
}

export function SalesOrderLifecycleApiResponseToJSON(json: any): SalesOrderLifecycleApiResponse {
    return SalesOrderLifecycleApiResponseToJSONTyped(json, false);
}

export function SalesOrderLifecycleApiResponseToJSONTyped(value?: SalesOrderLifecycleApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'companyId': value['companyId'],
        'makerId': value['makerId'],
        'status': value['status'],
        'version': value['version'],
        'lines': ((value['lines'] as Array<any>).map(SalesOrderLineApiResponseToJSON)),
        'transitions': (value['transitions'] == null ? null : (value['transitions'] as Array<any>).map(SalesOrderTransitionApiResponseToJSON)),
    };
}
