<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Modules\Accounting\Accounting.Domain\KaguERP.Modules.Accounting.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Parties\Parties.Domain\KaguERP.Modules.Parties.Domain.csproj" />
  </ItemGroup>
</Project>
